name: Code analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

env:
  SONARQUBE_PROJECT_KEY: "saf-example-pipeline"

jobs:
  code_analysis:
    name: Code analysis
    runs-on: ubuntu-20.04
    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: sonarqube scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: ${{ env.SONARQUBE_PROJECT_KEY }}
      - name: convert sonarqube scan to hdf
        uses: mitre/saf_action@v1
        with:
          command_string: "convert sonarqube2hdf -n ${{ env.SONARQUBE_PROJECT_KEY }} -u ${{ secrets.SONARQUBE_HOST }} --auth ${{ secrets.SONARQUBE_TOKEN }} -o sonarqube-hdf.json"
      - name: upload sonarqube hdf to heimdall
        run: 'curl --show-error --fail -F "data=@sonarqube-hdf.json" -F "public=true" -H "Authorization: ${{ secrets.HEIMDALL_API_KEY }}" "${{ secrets.HEIMDALL_HOST }}/evaluations"'
